controller:
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 256Mi

server:
  ingress:
    enabled: true
    ingressClassName: alb
    hostname: argocd.dev.mjkim.click
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.name: eks-sandbox-dev
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-path: /healthz
      alb.ingress.kubernetes.io/healthcheck-port: traffic-port
      alb.ingress.kubernetes.io/success-codes: "200"
      alb.ingress.kubernetes.io/certificate-arn: >-
        arn:aws:acm:ap-northeast-2:728138073365:certificate/1cd6458c-4b7f-4eea-98ce-4acb209259cc
      alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
      external-dns.alpha.kubernetes.io/hostname: argocd.dev.mjkim.click
    paths:
    - /
    pathType: Prefix
  resources:
    limits:
      cpu: 100m
      memory: 256Mi

repoServer:
  resources:
    limits:
      cpu: 1
      memory: 1Gi

configs:
  params:
    server.insecure: true

global:
  nodeSelector:
    eks.amazonaws.com/nodegroup: init
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"