image:
  repository: 728138073365.dkr.ecr.ap-northeast-2.amazonaws.com/eks-demo
  pullPolicy: IfNotPresent
  tag: "d470b5a52"

nameOverride: "eks-demo"
fullnameOverride: "eks-demo"
namespace: eks-demo

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::728138073365:role/eks-demo-dev-role

env:
  - name: AWS_REGION
    value: "ap-northeast-2"
  - name: SQS_QUEUE_NAME
    value: "eks-sandbox-dev-sqs"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "alb"
  annotations: 
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: eks-sandbox-dev
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: >-
      arn:aws:acm:ap-northeast-2:728138073365:certificate/1cd6458c-4b7f-4eea-98ce-4acb209259cc
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    external-dns.alpha.kubernetes.io/hostname: "eks-demo.dev.mjkim.click"  
  hosts:
    - host: eks-demo.dev.mjkim.click
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 2
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 5
  failureThreshold: 3
  timeoutSeconds: 2

serviceMonitor:
  enabled: true
  path: /actuator/prometheus
  interval: 15s