serviceAccount:
  create: true
  name: "external-secrets"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::728138073365:role/eks-sandbox-dev-external-secrets-role"

global:
  nodeSelector:
    eks.amazonaws.com/nodegroup: init
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"