namespaceOverride: kube-system
sources:
  - service
  - ingress
aws:
  region: ap-northeast-2
policy: sync
txtOwnerId: eks-sandbox-dev
serviceAccount:
  name: external-dns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::728138073365:role/eks-sandbox-dev-external-dns-role

nodeSelector:
  eks.amazonaws.com/nodegroup: init
tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"