serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::728138073365:role/eks-sandbox-dev-karpenter-controller

settings:
  clusterName: eks-sandbox-dev
  # Terraform으로 EKS 클러스터 생성 후 cluseterEndpoint를 필수 주입
  clusterEndpoint: "https://78CD04F315B9B509F9BCABCEE96ACBF9.sk1.ap-northeast-2.eks.amazonaws.com"

controller:
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 1Gi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: karpenter.sh/nodepool
          operator: DoesNotExist
        - key: eks.amazonaws.com/nodegroup
          operator: In
          values:
          - init
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: "kubernetes.io/hostname"
