nodeSelector:
  eks.amazonaws.com/nodegroup: init
tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"

podDisruptionBudget:
  operator:
    minAvailable: 1
  metricServer:
    minAvailable: 1
    
prometheus:
  metricServer:
    enabled: true
    serviceMonitor:
      enabled: true
  operator:
    enabled: true
    serviceMonitor:
      enabled: true

resources:
  limits:
    cpu: 10m
    memory: 64Mi
  requests:
    cpu: 100m
    memory: 128Mi