apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: eks-sandbox-prod
spec:
  role: arn:aws:iam::728138073365:role/eks-sandbox-prod-karpenter-node
  amiSelectorTerms:
    - alias: "al2023@v20260423"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-sandbox-prod
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-sandbox-prod
  blockDeviceMappings:
    - deviceName: /prod/xvda
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
        encrypted: true
        kmsKeyID: "alias/aws/ebs"
        deleteOnTermination: true
  tags:
      Name: "eks-sandbox-prod-karpenter-node"
      Project: "eks-sandbox-prod"
      Owner: "minyx"
      Terraform: "false"