apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-webhook
  namespace: monitoring
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-ssm-parameter-store
    kind: ClusterSecretStore
  target:
    name: slack-webhook-secret
    creationPolicy: Owner
  data:
    - secretKey: slack-webhook
      remoteRef:
        key: /eks-sandbox/prod/alertmanager/slack-webhook