apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-slack-secret
  namespace: monitoring
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-ssm-parameter-store
    kind: ClusterSecretStore
  target:
    name: alertmanager-slack-secret
    creationPolicy: Owner
  data:
    - secretKey: slack-webhook-url
      remoteRef:
        key: /eks-sandbox/prod/alertmanager/slack-webhook

---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-ssm-parameter-store
    kind: ClusterSecretStore
  target:
    name: grafana-admin-secret
    creationPolicy: Owner
    template:
      data:
        admin-user: "admin"
        admin-password: "{{ .password }}"
    data:
      - secretKey: password
        remoteRef:
          key: /eks-sandbox/prod/grafana/admin-password