apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-demo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mjkim134/eks-sandbox.git
    targetRevision: HEAD
    path: helm/eks-demo-app
    helm:
      valueFiles:
        - kimpala-dev-values.yaml
      parameters:
        - name: image.repository
          value: "<AWS_ACCOUNT_NUM>.dkr.ecr.ap-northeast-2.amazonaws.com/eks-demo"
      parameters:
        - name: ingress.annotations.alb.ingress.kubernetes.io/certificate-arn
          value: "arn:aws:acm:ap-northeast-2:<AWS_ACCOUNT_NUM>:certificate/4a1e6268-b3a2-4ce2-8482-2e891acecc89"
  destination:
    server: https://kubernetes.default.svc
    namespace: eks-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true