metadata:
  name: ""

clusterName: ""
env: ""

nodePool:
  arch:
    - ""
  capacityTypes:
    - ""
  instanceTypes:
    - ""
  expireAfter: "720h"
  limitCpu: 1000
  limitMemory: 1000Gi

nodeClass:
  role: ""