apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  role: {{ .Values.nodeClass.role }}
  amiSelectorTerms:
    - alias: "al2023@v20260423"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.clusterName }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.clusterName }}
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true
  tags:
      Name: {{ .Values.nodeName }}
      Service: "Test"
      Organization: "tech"
      Team: "tech/devops"
      Resource: "eks"
      Env: {{ .Values.env | quote }}
      Terraformed: "true"