controller:
  nodeSelector:
    eks.amazonaws.com/nodegroup: init
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi