clusterName: eks-sandbox-prod
serviceAccount:
  create: true
  name: aws-load-balancer-controller
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::728138073365:role/eks-sandbox-prod-load-balancer-controller-role
region: ap-northeast-2
vpcId: vpc-05b43f9ffe96f3e76

nodeSelector:
  eks.amazonaws.com/nodegroup: init
tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

podDisruptionBugdet:
  maxUnavailable: 1