image:
  repository: 728138073365.dkr.ecr.ap-northeast-2.amazonaws.com/eks-sandbox
  pullPolicy: IfNotPresent
  tag:

nameOverride: "eks-demo"
fullnameOverride: "eks-demo"
namespace: eks-demo

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::728138073365:role/eks-sandbox-dev-eks-demo-role

env:
  - name: AWS_REGION
    value: "ap-northeast-2"
  - name: SQS_QUEUE_NAME
    value: "eks-demo-prod-sqs"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "alb"
  annotations: 
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: eks-sandbox-prod
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: >-
      arn:aws:acm:ap-northeast-2:728138073365:certificate/f3aaf897-268a-4f94-9bce-fd690feeb8c9
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    external-dns.alpha.kubernetes.io/hostname: "eks-demo.mjkim.click"  
  hosts:
    - host: eks-demo.mjkim.click
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 2
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 5
  failureThreshold: 3
  timeoutSeconds: 2

serviceMonitor:
  enabled: true
  path: /actuator/prometheus
  interval: 15s

replicaCount: 2

podDisruptionBudget:
  enabled: true
  minAvailable: 1

keda:
  minReplicaCount: 5
  maxReplicaCount: 20
  awsSQSQueue:
    queueURL: https://sqs.ap-northeast-2.amazonaws.com/728138073365/eks-demo-prod-sqs
    queueLength: "500"
  cpu:
    value: "70"

rollout:
  canary:
    steps:
      - setWeight: 20
      - pause: {duration: 5m}