namespaceOverride: kube-system
sources:
  - service
  - ingress
aws:
  region: ap-northeast-2
policy: sync
txtOwnerId: eks-sandbox-prod
serviceAccount:
  name: external-dns
  annotations:
    eks.amazonaws.com/role-arn: 

nodeSelector:
  eks.amazonaws.com/nodegroup: init
tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"