metadata:
  name: eks-sandbox-prod

clusterName: "eks-sandbox-prod"
nodeName: "eks-sandbox-prod-karpenter-node"
env: "prod"

nodePool:
  arch:
    - "amd64"
  capacityTypes:
    - "on-demand"
  instanceTypes:
    - "m7i.large"
  expireAfter: "720h"
  limitCpu: 1000
  limitMemory: 1000Gi

nodeClass:
  role: arn:aws:iam::728138073365:role/eks-sandbox-prod-karpenter-node