serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::728138073365:role/eks-sandbox-prod-karpenter-controller

settings:
  clusterName: eks-sandbox-prod
  # Terraform으로 EKS 클러스터 생성 후 cluseterEndpoint를 필수 주입
  clusterEndpoint: "https://6B471FAD661518228BACE7FFDDE6427D.gr7.ap-northeast-2.eks.amazonaws.com"

controller:
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2
      memory: 2Gi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: karpenter.sh/nodepool
          operator: DoesNotExist
        - key: eks.amazonaws.com/nodegroup
          operator: In
          values:
          - init
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: "kubernetes.io/hostname"