apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1" 
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 87.9.0
      helm:
        valueFiles:
          - $eks-sandbox/helm-values/dev/prometheus-values.yaml
          - $eks-sandbox/helm-values/dev/grafana-values.yaml
          - $eks-sandbox/helm-values/dev/alertmanager-values.yaml
    - repoURL: https://github.com/mjkim134/eks-sandbox.git
      targetRevision: HEAD
      ref: eks-sandbox
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true