spring:
  application:
    name: eks-demo

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true