serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::728138073365:role/KarpenterControllerRole-kimpala-dev

settings:
  clusterName: kimpala-dev

controller:
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 1Gi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: karpenter.sh/nodepool
          operator: DoesNotExist
        - key: eks.amazonaws.com/nodegroup
          operator: In
          values:
          - karpenter-2026050704123894550000001a
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: "kubernetes.io/hostname"