clusterName: kimpala-dev
serviceAccount:
  create: true
  name: aws-load-balancer-controller
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::728138073365:role/load-balancer-controller-20260615033520207900000010