apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: eks-demo-autoscaler
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ include "eks-demo.fullname" . }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  triggers:
    - type: aws-sqs-queue
      authenticationRef:
        name: aws-sqs-auth
      metadata:
        queueURL: {{ .Values.keda.awsSQSQueue.queueURL }}
        awsRegion: ap-northeast-2
        queueLength: {{ .Values.keda.awsSQSQueue.queueLength | quote }}
    - type: cpu
      metadata:
        metricType: Utilization
        value: {{ .Values.keda.cpu.value | quote }}