apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .Values.metadata.name }}
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
{{- toYaml .Values.nodePool.arch | nindent 12 }}
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values:
{{- toYaml .Values.nodePool.capacityTypes | nindent 12 }}
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
{{- toYaml .Values.nodePool.instanceTypes | nindent 12 }}
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      expireAfter: {{ .Values.nodePool.expireAfter}}
  limits:
    cpu: {{ .Values.nodePool.limitCpu }}
    memory: {{ .Values.nodePool.limitMemory}}
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m