server:
  ingress:
    enabled: true
    ingressClassName: alb
    hostname: argocd.mjkim.click
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.name: shared-alb
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-path: /healthz
      alb.ingress.kubernetes.io/healthcheck-port: traffic-port
      alb.ingress.kubernetes.io/success-codes: "200"
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:728138073365:certificate/4a1e6268-b3a2-4ce2-8482-2e891acecc89
      alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
      external-dns.alpha.kubernetes.io/hostname: argocd.mjkim.click
    paths:
    - /
    pathType: Prefix

configs:
  params:
    server.insecure: true