namespaceOverride: kube-system
sources:
  - service
  - ingress
aws:
  region: ap-northeast-2
policy: sync
txtOwnerId: kimpala-dev
serviceAccount:
  name: external-dns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::728138073365:role/external-dns-2026062311331062500000000e