apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secondary-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mjkim134/eks-sandbox.git
    targetRevision: HEAD
    path: gitops/envs/prod/secondary-application
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false